export class SecurityEvent {
	constructor(
		public id: number,
		public sucesoRelacionado: number,
		public perfilReportante: number,
		public unidadPresento: number,
		public unidadReporto: number,
		public servicioPresento: number,
		public direccionAsistencial: number,
		public tipoIdentificacion: string,
		public numeroIdentificacion: number,
		public nombresApellidos: string,
		public edadPaciente: number,
		public genero: string,
		public aseguradora: string,
		public gestante: number,
		public fechaSuceso: string,
		public horaSuceso: string,
		public descripcionSuceso: string,
		public tensionArterial: string,
		public temperatura: number,
		public frecuenciaRespiratoria: number,
		public frecuenciaCardiaca: number,
		public SPO2: number,
		public glucometria: number,
		public glasgow: number,
		public peso: number,

		public equipoMedico: string,
		public marca: string,
		public referencia: string,
		public modelo: string,
		public lote: string,
		public serial: string,

		public tipoMedicamento: string,
		public nombreGenericoMedicamento: string,
		public nombreComercialMedicamento: string,
		public laboratorioComercialMedicamento: string,
		public loteMedicamento: string,
		public registroSanitarioMedicamento: string,
		public fechaVencimientoMedicamento: string,

		public nombreHemocomponente: number,
		public loteHemocomponente: string,
		public fechaVencimientoHemocomponente: string,
		public numeroAdministradoHemocomponente: number,
		public fechaAdministradoHemocomponente: string,
		public horaAdministradoHemocomponente: string,
		public fechaReaccionHemocomponente: string,
		public horaReaccionHemocomponente: string,
		public antecedentesTransfusionales: string,
		public identificacionReaccionAdverso: string,
		public grupoSanguineo: number,

		public nombreComercialReactivo: string,
		public registroSanitarioReactivo: string,
		public loteReactivo: string,
		public fechaVencimientoReactivo: string,
		public procedenciaReactivo: string,
		public cadenaFrioReactivo: number,
		public nombreImportadorReactivo: string,
		public temperaturaAlmacenadoReactivo: string,
		public condicionesAlmacenadoReactivo: number,
		public servicioFuncionamientoReactivo: number,
		public certificadoAnalisisReactivo: number,

		public archivo: string, 
	){}
}
				     		