export class ReferalRequest {
	constructor(
		public id: number,
		public numeroIdentificacion: number,
		public tipoIdentificacion: string,
		public nombresApellidos: string,
		public edadPaciente: number,
		public genero: string,
		public aseguradora: string,

		public ingreso: number,
		public centroAtencion: string,
		public numeroCama: string,
		public nombreCama: string,
		public motivoTraslado: number,

		public folio: string,
		public fechaFolio: string,
		public diagnostico: string,
		public nombreMedico: string,
		public especialidadMedico: string,
		public ambulancia: number,
		public prioridad: number,
		public estado: number,

		public fechaHoraAceptacion: string,	
		public funcionarioContesta: string,
		public sedeContestan: string,
		public numeroMovil: string,
		public tipoTraslado: number,
		public fechaDespacho: string,
		public horaDespacho: string,
		public fechaLlegadaOrigen: string,
		public horaLlegadaOrigen: string,
		public fechaSalidaOrigen: string,
		public horaSalidaOrigen: string,
		public fechaLlegadaDestino: string,
		public horaLlegadaDestino: string,
		public fechaSalidaDestino: string,
		public horaSalidaDestino: string,
		public fechaRegreso: string,
		public horaRegreso: string,
		public fechaHoraCierre: string,
	) {}
}